### ISSUE TITLE
Stuck at BLE saga started

### ISSUE THREAD

**Issue by CR1AT0RS** [Cierpliwy/SensorTagExpo#1]
App start:
1. Scanning started
2. BLE state changed to PoweredOn
2. BLE saga started 

I can see the devices getting searched in debug logs. But the search continues forever is this intentional? I think it should list all devices as soon as it find them. 

![IMG_0163](https://user-images.githubusercontent.com/4299288/65489483-190cb280-de60-11e9-8996-9fe9a4ab9e1c.PNG)

w

**Comment by tigerzhang** [comment]
@CR1AT0RS Same problem here. How did you fix it?
